# Generated by Django 5.0 on 2024-03-23 15:31

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', django_ckeditor_5.fields.CKEditor5Field(max_length=200, verbose_name='Название')),
                ('desc', django_ckeditor_5.fields.CKEditor5Field(max_length=500, verbose_name='Краткое описание')),
                ('desc_main', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Полное описание')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='СountryModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название страны:')),
                ('country_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Код страны')),
            ],
            options={
                'verbose_name': 'Страну',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('i_agree', models.BooleanField(default=False, verbose_name='Большой размер')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main.cards')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.AddField(
            model_name='cards',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='main.сountrymodels', verbose_name='Страна'),
        ),
    ]
