# Generated by Django 5.0 on 2024-03-23 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_citymodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='main.citymodels', verbose_name='Город'),
        ),
    ]
