# Generated by Django 5.0.3 on 2024-03-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_cards_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="cards",
            name="bedrooms",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cards",
            name="distances_to_the_sea",
            field=models.CharField(
                choices=[("first_line", "Первая линия"), ("500", "500 Метров")],
                default="500",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="cards",
            name="hot_offers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cards",
            name="new_building",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cards",
            name="price",
            field=models.IntegerField(null=True),
        ),
    ]
